### PR TITLE
Support SQLAlchemy 2.0

### PR DESCRIPTION
**Pull request by rongxin-liu**

### CODE REVIEW

**Comment by rongxin-liu** [comment]
Tested with `finance` and `movies` problem sets.

**Comment by Jelleas** [comment]
Hi Rongxin! I just ran into this issue too, would love a merge on this PR :)

Quick double check, shouldn't this one be wrapped with `sqlalchemy.text()` too?

https://github.com/cs50/python-cs50/blob/0608340a51d5fc60742b4a94ab3f9b45e7d45f2a/src/cs50/sql.py#L86

**Comment by rongxin-liu** [comment]
> Hi Rongxin! I just ran into this issue too, would love a merge on this PR :)
> 
> Quick double check, shouldn't this one be wrapped with `sqlalchemy.text()` too?
> 
> https://github.com/cs50/python-cs50/blob/0608340a51d5fc60742b4a94ab3f9b45e7d45f2a/src/cs50/sql.py#L86

Hey, here we're executing a SQL statement directly using a database cursor (sqlite3 backend), not the SQLAlchemy engine so I think this usage does not need to be or should be replaced with sqlalchemy.text().

**Comment by Jelleas** [comment]
🥳 thanks!

**Pull request merged**
