### PR TITLE
Update sql.py

### PR DESCRIPTION
**Pull request by igorvoltaic**
Functionality which commits changes to Postgres DB
https://www.postgresql.org/docs/8.3/sql-commit.html

### CODE REVIEW

**Comment by kzidane** [comment]
What are you trying to do exactly, @igorvoltaic?

**Comment by igorvoltaic** [comment]
Hi Kareem,

I've been following the guide to deploy my app to Heroku and spent quite some time trying to understand why non of the changes to Prostges aren't persistent 

Here is an example:
```

Python 3.7.6 (default, Mar  6 2020, 22:15:44) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from cs50 import SQL
>>> db = SQL("postgres://URI?sslmode=require")
>>> warehouses = db.execute("SELECT id, name, address, status FROM warehouses")
>>> warehouses
[]
>>> db.execute("INSERT INTO warehouses (name, address, status) VALUES (:name, :address, :status);", name='wh-1', address='add-1', status=1)
1
>>> warehouses = db.execute("SELECT id, name, address, status FROM warehouses")
>>> warehouses
[{'id': 1, 'name': 'wh-1', 'address': 'add-1', 'status': 1}]
>>> 
>>> 
>>> 
>>> 
>>> db = SQL("postgres://URI?sslmode=require")
>>> warehouses = db.execute("SELECT id, name, address, status FROM warehouses")
>>> warehouses
[]
>>>
```

Turns out you need to issue `COMMIT` statement for changes to be persistent in Postgres.

Also Travis tells me I need to do more testing  first :)

**Comment by igorvoltaic** [comment]
Just checked the lib (sql.py) locally, everything works as intended:

```
Python 3.7.6 (default, Mar  6 2020, 22:15:44) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sql import SQL
>>> db = SQL("postgres://URI?sslmode=require")
>>> warehouses = db.execute("SELECT id, name, address, status FROM warehouses")
>>> warehouses
[]
>>> db.execute("INSERT INTO warehouses (name, address, status) VALUES (:name, :address, :status);", name='wh-1', address='add-1', status=1)
>>> warehouses = db.execute("SELECT id, name, address, status FROM warehouses")
>>> warehouses
[{'id': 2, 'name': 'wh-1', 'address': 'add-1', 'status': 1}]
>>> 
>>> 
>>> 
>>>
>>> db = SQL("postgres://URI?sslmode=require")
>>> warehouses = db.execute("SELECT id, name, address, status FROM warehouses")
>>> warehouses
[{'id': 2, 'name': 'wh-1', 'address': 'add-1', 'status': 1}]
>>> 
```

**Comment by dmalan** [comment]
Thank you for catching this, @igorvoltaic. We're about to deploy a broader set of changes to handle transactions more robustly!

https://github.com/cs50/python-cs50/pull/122

**Pull request closed without merging**
