### PR TITLE
grays out site packages in tracebacks

### PR DESCRIPTION
**Pull request by dmalan**
If user does `import cs50` or `from cs50 import...`, tracebacks are darkened per below.

# CLI

## before

cli2-before

cli-before

## after

cli2-after

cli-after

# Flask

## before

flask-before

## after

flask-after

### CODE REVIEW

**Comment by dmalan** [comment]
@glennholloway @kzidane @crossroads1112 @brianyu28 what do you think? Much like the library transparently disables stdout/stderr buffering, so is this feature meant to facilitate development and debugging for students. Rather than hide system files altogether, it simply grays them out to highlight students' own code.

**Comment by dmalan** [comment]
PS, it's enabled simply by doing

```
import cs50
```

or

```
from cs50 import something
```

atop one's own program.

**Comment by dmalan** [comment]
@glennholloway @kzidane @crossroads1112 @brianyu28, updated screenshots and code itself. Adds Flask support now.

**Comment by dmalan** [comment]
@brianyu28 mind testing this out before I merge?

**Comment by brianyu28** [comment]
Tested, seems to work on the errors I tried!

**Pull request merged**
