### PR TITLE
s/isinstance/type/

### PR DESCRIPTION
**Pull request by kzidane**

### CODE REVIEW

**Comment by kzidane** [comment]
@dmalan I think they're practically the same in this case. Changed to `is` for readability.

**Comment by dmalan** [comment]
Does practically mean there's some difference though?

**Comment by dmalan** [comment]
Right, but what does "practically the same in this case" mean? :)

**Comment by kzidane** [comment]
Because the class instances we're comparing are singleton so using either (e.g., `is` or `==`) should evaluate to the same value.

```
>>> type(42) == int == type(42) is int
True
```

**Pull request merged**
