### PR TITLE
Fix SQL error for pset8 finance

### PR DESCRIPTION
**Pull request by chrisgzf**
After #83, users were facing errors with the CS50 SQL module with pset8 finance. The error occurs whenever the webserver is started and somebody visits the page. https://www.reddit.com/r/cs50/comments/cbez89/finance_nameerror_name_self_is_not_defined/etfi05q/

```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 303, in run_wsgi
execute(self.server.app)
File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 291, in execute
application_iter = app(environ, start_response)
File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/home/ubuntu/2019/pset8/finance/application.py", line 36, in <module>
db = SQL("sqlite:///finance.db")
File "/usr/local/lib/python3.7/site-packages/cs50/sql.py", line 66, in __init__
self.execute("SELECT 1")
File "/usr/local/lib/python3.7/site-packages/cs50/flask.py", line 40, in _after
return _before(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 423, in __init__
instance_path = self.auto_find_instance_path()
AttributeError: 'SQL' object has no attribute 'auto_find_instance_path'
```

This is due to the monkey-patch swapping the `SQL.SQL.execute` function wrongly. This PR fixes that bug.

Tested with running pset8 finance.

### CODE REVIEW

**Comment by chrisgzf** [comment]
Woops, I just realised it actually was swapping out the function correctly, because `from .sql import SQL` was used. Something is up....

**Comment by chrisgzf** [comment]
This issue arises due to a namespace conflict. Flask's `_after` and `_before` are getting mixed up with SQL's `_after` and `_before`, causing SQL to call the Flask's `__init__`. Pushing a fix now.

**Comment by chrisgzf** [comment]
Committed my fix! Hope my diagnosis is correct and that this bug-fix doesn't create any additional bugs like my previous bug-fix did...

**Comment by kzidane** [comment]
Good catch! Thanks! https://github.com/cs50/python-cs50/pull/85

**Pull request closed without merging**
